/*
File: kaggle_schema.sql
Date Created: 2018-10-12
Author(s): Mahkah Wu
Purpose: SQL to create tables housing baseball data retireved from kaggle. Generated using csvkit.
*/

CREATE TABLE "allstar_full" (
	"playerID" VARCHAR NOT NULL,
	"yearID" DECIMAL NOT NULL,
	"gameNum" DECIMAL NOT NULL,
	"gameID" VARCHAR,
	"teamID" VARCHAR NOT NULL,
	"lgID" VARCHAR NOT NULL,
	"GP" BOOLEAN,
	"startingPos" DECIMAL
);


CREATE TABLE "appearances" (
	"yearID" DECIMAL NOT NULL,
	"teamID" VARCHAR NOT NULL,
	"lgID" VARCHAR,
	"playerID" VARCHAR NOT NULL,
	"G_all" DECIMAL NOT NULL,
	"GS" DECIMAL,
	"G_batting" DECIMAL NOT NULL,
	"G_defense" DECIMAL NOT NULL,
	"G_p" DECIMAL NOT NULL,
	"G_c" DECIMAL NOT NULL,
	"G_1b" DECIMAL NOT NULL,
	"G_2b" DECIMAL NOT NULL,
	"G_3b" DECIMAL NOT NULL,
	"G_ss" DECIMAL NOT NULL,
	"G_lf" DECIMAL NOT NULL,
	"G_cf" DECIMAL NOT NULL,
	"G_rf" DECIMAL NOT NULL,
	"G_of" DECIMAL NOT NULL,
	"G_dh" DECIMAL,
	"G_ph" DECIMAL,
	"G_pr" DECIMAL
);


CREATE TABLE "awards_managers" (
	"playerID" VARCHAR NOT NULL,
	"awardID" VARCHAR NOT NULL,
	"yearID" DECIMAL NOT NULL,
	"lgID" VARCHAR NOT NULL,
	"tie" BOOLEAN,
	"notes" BOOLEAN
);


CREATE TABLE "awards_players" (
	"playerID" VARCHAR NOT NULL,
	"awardID" VARCHAR NOT NULL,
	"yearID" DECIMAL NOT NULL,
	"lgID" VARCHAR NOT NULL,
	"tie" BOOLEAN,
	"notes" VARCHAR
);


CREATE TABLE "awards_share_managers" (
	"awardID" VARCHAR NOT NULL,
	"yearID" DECIMAL NOT NULL,
	"lgID" VARCHAR NOT NULL,
	"playerID" VARCHAR NOT NULL,
	"pointsWon" DECIMAL NOT NULL,
	"pointsMax" DECIMAL,
	"votesFirst" DECIMAL NOT NULL
);


CREATE TABLE "award_share_players" (
	"awardID" VARCHAR NOT NULL,
	"yearID" DECIMAL NOT NULL,
	"lgID" VARCHAR NOT NULL,
	"playerID" VARCHAR NOT NULL,
	"pointsWon" DECIMAL NOT NULL,
	"pointsMax" DECIMAL NOT NULL,
	"votesFirst" DECIMAL
);


CREATE TABLE "batting" (
	"playerID" VARCHAR NOT NULL,
	"yearID" DECIMAL NOT NULL,
	"stint" DECIMAL NOT NULL,
	"teamID" VARCHAR NOT NULL,
	"lgID" VARCHAR,
	"G" DECIMAL NOT NULL,
	"AB" DECIMAL NOT NULL,
	"R" DECIMAL NOT NULL,
	"H" DECIMAL NOT NULL,
	"2B" DECIMAL NOT NULL,
	"3B" DECIMAL NOT NULL,
	"HR" DECIMAL NOT NULL,
	"RBI" DECIMAL,
	"SB" DECIMAL,
	"CS" DECIMAL,
	"BB" DECIMAL NOT NULL,
	"SO" DECIMAL,
	"IBB" DECIMAL,
	"HBP" DECIMAL,
	"SH" DECIMAL,
	"SF" DECIMAL,
	"GIDP" DECIMAL
);


CREATE TABLE "batting_post" (
	"yearID" DECIMAL NOT NULL,
	"round" VARCHAR NOT NULL,
	"playerID" VARCHAR NOT NULL,
	"teamID" VARCHAR NOT NULL,
	"lgID" VARCHAR NOT NULL,
	"G" DECIMAL NOT NULL,
	"AB" DECIMAL NOT NULL,
	"R" DECIMAL NOT NULL,
	"H" DECIMAL NOT NULL,
	"2B" DECIMAL NOT NULL,
	"3B" DECIMAL NOT NULL,
	"HR" DECIMAL NOT NULL,
	"RBI" DECIMAL NOT NULL,
	"SB" DECIMAL NOT NULL,
	"CS" DECIMAL,
	"BB" DECIMAL NOT NULL,
	"SO" DECIMAL NOT NULL,
	"IBB" DECIMAL NOT NULL,
	"HBP" DECIMAL,
	"SH" DECIMAL,
	"SF" DECIMAL,
	"GIDP" DECIMAL
);


CREATE TABLE "college_playing" (
	"playerID" VARCHAR NOT NULL,
	"schoolID" VARCHAR NOT NULL,
	"yearID" DECIMAL NOT NULL
);


CREATE TABLE "fielding" (
	"playerID" VARCHAR NOT NULL,
	"yearID" DECIMAL NOT NULL,
	"stint" DECIMAL NOT NULL,
	"teamID" VARCHAR NOT NULL,
	"lgID" VARCHAR,
	"POS" VARCHAR NOT NULL,
	"G" DECIMAL NOT NULL,
	"GS" DECIMAL,
	"InnOuts" DECIMAL,
	"PO" DECIMAL NOT NULL,
	"A" DECIMAL,
	"E" DECIMAL,
	"DP" DECIMAL,
	"PB" DECIMAL,
	"WP" DECIMAL,
	"SB" DECIMAL,
	"CS" DECIMAL,
	"ZR" DECIMAL
);


CREATE TABLE "fielding_of" (
	"playerID" VARCHAR NOT NULL,
	"yearID" DECIMAL NOT NULL,
	"stint" DECIMAL NOT NULL,
	"Glf" DECIMAL,
	"Gcf" DECIMAL,
	"Grf" DECIMAL
);


CREATE TABLE "fielding_of_split" (
	"playerID" VARCHAR NOT NULL,
	"yearID" DECIMAL NOT NULL,
	"stint" DECIMAL NOT NULL,
	"teamID" VARCHAR NOT NULL,
	"lgID" VARCHAR NOT NULL,
	"POS" VARCHAR NOT NULL,
	"G" DECIMAL NOT NULL,
	"GS" DECIMAL,
	"InnOuts" DECIMAL,
	"PO" DECIMAL,
	"A" DECIMAL,
	"E" DECIMAL,
	"DP" DECIMAL,
	"PB" BOOLEAN,
	"WP" BOOLEAN,
	"SB" BOOLEAN,
	"CS" BOOLEAN,
	"ZR" BOOLEAN
);


CREATE TABLE "fielding_post" (
	"playerID" VARCHAR NOT NULL,
	"yearID" DECIMAL NOT NULL,
	"teamID" VARCHAR NOT NULL,
	"lgID" VARCHAR NOT NULL,
	"round" VARCHAR NOT NULL,
	"POS" VARCHAR NOT NULL,
	"G" DECIMAL NOT NULL,
	"GS" DECIMAL NOT NULL,
	"InnOuts" DECIMAL NOT NULL,
	"PO" DECIMAL NOT NULL,
	"A" DECIMAL NOT NULL,
	"E" DECIMAL NOT NULL,
	"DP" DECIMAL NOT NULL,
	"TP" BOOLEAN NOT NULL,
	"PB" DECIMAL,
	"SB" DECIMAL,
	"CS" DECIMAL
);


CREATE TABLE "hall_of_fame" (
	"playerID" VARCHAR NOT NULL,
	"yearid" DECIMAL NOT NULL,
	"votedBy" VARCHAR NOT NULL,
	"ballots" DECIMAL,
	"needed" DECIMAL,
	"votes" DECIMAL,
	"inducted" BOOLEAN NOT NULL,
	"category" VARCHAR NOT NULL,
	needed_note VARCHAR
);


CREATE TABLE "home_games" (
	"year.key" DECIMAL NOT NULL,
	"league.key" VARCHAR,
	"team.key" VARCHAR NOT NULL,
	"park.key" VARCHAR NOT NULL,
	"span.first" DATE NOT NULL,
	"span.last" DATE NOT NULL,
	"games" DECIMAL NOT NULL,
	"openings" DECIMAL NOT NULL,
	"attendance" DECIMAL NOT NULL
);


CREATE TABLE "managers" (
	"playerID" VARCHAR NOT NULL,
	"yearID" DECIMAL NOT NULL,
	"teamID" VARCHAR NOT NULL,
	"lgID" VARCHAR,
	"inseason" DECIMAL NOT NULL,
	"G" DECIMAL NOT NULL,
	"W" DECIMAL NOT NULL,
	"L" DECIMAL NOT NULL,
	"rank" DECIMAL,
	"plyrMgr" BOOLEAN NOT NULL
);


CREATE TABLE "managers_half" (
	"playerID" VARCHAR NOT NULL,
	"yearID" DECIMAL NOT NULL,
	"teamID" VARCHAR NOT NULL,
	"lgID" VARCHAR NOT NULL,
	"inseason" DECIMAL NOT NULL,
	"half" DECIMAL NOT NULL,
	"G" DECIMAL NOT NULL,
	"W" DECIMAL NOT NULL,
	"L" DECIMAL NOT NULL,
	"rank" DECIMAL NOT NULL
);


CREATE TABLE "master" (
	"playerID" VARCHAR NOT NULL,
	"birthYear" DECIMAL,
	"birthMonth" DECIMAL,
	"birthDay" DECIMAL,
	"birthCountry" VARCHAR,
	"birthState" VARCHAR,
	"birthCity" VARCHAR,
	"deathYear" DECIMAL,
	"deathMonth" DECIMAL,
	"deathDay" DECIMAL,
	"deathCountry" VARCHAR,
	"deathState" VARCHAR,
	"deathCity" VARCHAR,
	"nameFirst" VARCHAR,
	"nameLast" VARCHAR NOT NULL,
	"nameGiven" VARCHAR,
	"weight" DECIMAL,
	"height" DECIMAL,
	"bats" VARCHAR,
	"throws" VARCHAR,
	"debut" DATE,
	"finalGame" DATE,
	"retroID" VARCHAR,
	"bbrefID" VARCHAR
);


CREATE TABLE "parks" (
	"park.key" VARCHAR NOT NULL,
	"park.name" VARCHAR NOT NULL,
	"park.alias" VARCHAR,
	"city" VARCHAR NOT NULL,
	"state" VARCHAR,
	"country" VARCHAR NOT NULL
);


CREATE TABLE "pitching" (
	"playerID" VARCHAR NOT NULL,
	"yearID" DECIMAL NOT NULL,
	"stint" DECIMAL NOT NULL,
	"teamID" VARCHAR NOT NULL,
	"lgID" VARCHAR,
	"W" DECIMAL NOT NULL,
	"L" DECIMAL NOT NULL,
	"G" DECIMAL NOT NULL,
	"GS" DECIMAL NOT NULL,
	"CG" DECIMAL NOT NULL,
	"SHO" DECIMAL NOT NULL,
	"SV" DECIMAL NOT NULL,
	"IPouts" DECIMAL NOT NULL,
	"H" DECIMAL NOT NULL,
	"ER" DECIMAL NOT NULL,
	"HR" DECIMAL NOT NULL,
	"BB" DECIMAL NOT NULL,
	"SO" DECIMAL NOT NULL,
	"BAOpp" DECIMAL,
	"ERA" DECIMAL,
	"IBB" DECIMAL,
	"WP" DECIMAL,
	"HBP" DECIMAL,
	"BK" DECIMAL NOT NULL,
	"BFP" DECIMAL,
	"GF" DECIMAL,
	"R" DECIMAL NOT NULL,
	"SH" DECIMAL,
	"SF" DECIMAL,
	"GIDP" DECIMAL
);


CREATE TABLE "pitching_post" (
	"playerID" VARCHAR NOT NULL,
	"yearID" DECIMAL NOT NULL,
	"round" VARCHAR NOT NULL,
	"teamID" VARCHAR NOT NULL,
	"lgID" VARCHAR NOT NULL,
	"W" DECIMAL NOT NULL,
	"L" DECIMAL NOT NULL,
	"G" DECIMAL NOT NULL,
	"GS" DECIMAL NOT NULL,
	"CG" DECIMAL NOT NULL,
	"SHO" DECIMAL NOT NULL,
	"SV" DECIMAL NOT NULL,
	"IPouts" DECIMAL NOT NULL,
	"H" DECIMAL NOT NULL,
	"ER" DECIMAL NOT NULL,
	"HR" DECIMAL NOT NULL,
	"BB" DECIMAL NOT NULL,
	"SO" DECIMAL NOT NULL,
	"BAOpp" DECIMAL,
	"ERA" VARCHAR,
	"IBB" DECIMAL,
	"WP" DECIMAL,
	"HBP" DECIMAL,
	"BK" BOOLEAN,
	"BFP" DECIMAL,
	"GF" DECIMAL NOT NULL,
	"R" DECIMAL NOT NULL,
	"SH" DECIMAL,
	"SF" DECIMAL,
	"GIDP" DECIMAL
);


CREATE TABLE "salaries" (
	"yearID" DECIMAL NOT NULL,
	"teamID" VARCHAR NOT NULL,
	"lgID" VARCHAR NOT NULL,
	"playerID" VARCHAR NOT NULL,
	"salary" DECIMAL NOT NULL
);


CREATE TABLE "schools" (
	"schoolID" VARCHAR NOT NULL,
	name_full VARCHAR NOT NULL,
	"city" VARCHAR NOT NULL,
	"state" VARCHAR NOT NULL,
	"country" VARCHAR NOT NULL
);


CREATE TABLE "series_post" (
	"yearID" DECIMAL NOT NULL,
	"round" VARCHAR NOT NULL,
	"teamIDwinner" VARCHAR NOT NULL,
	"lgIDwinner" VARCHAR NOT NULL,
	"teamIDloser" VARCHAR NOT NULL,
	"lgIDloser" VARCHAR NOT NULL,
	"wins" DECIMAL NOT NULL,
	"losses" DECIMAL NOT NULL,
	"ties" BOOLEAN NOT NULL
);


CREATE TABLE "teams" (
	"yearID" DECIMAL NOT NULL,
	"lgID" VARCHAR,
	"teamID" VARCHAR NOT NULL,
	"franchID" VARCHAR NOT NULL,
	"divID" VARCHAR,
	"Rank" DECIMAL NOT NULL,
	"G" DECIMAL NOT NULL,
	"Ghome" DECIMAL,
	"W" DECIMAL NOT NULL,
	"L" DECIMAL NOT NULL,
	"DivWin" BOOLEAN,
	"WCWin" BOOLEAN,
	"LgWin" BOOLEAN,
	"WSWin" BOOLEAN,
	"R" DECIMAL NOT NULL,
	"AB" DECIMAL NOT NULL,
	"H" DECIMAL NOT NULL,
	"2B" DECIMAL NOT NULL,
	"3B" DECIMAL NOT NULL,
	"HR" DECIMAL NOT NULL,
	"BB" DECIMAL NOT NULL,
	"SO" DECIMAL,
	"SB" DECIMAL,
	"CS" DECIMAL,
	"HBP" DECIMAL,
	"SF" DECIMAL,
	"RA" DECIMAL NOT NULL,
	"ER" DECIMAL NOT NULL,
	"ERA" DECIMAL NOT NULL,
	"CG" DECIMAL NOT NULL,
	"SHO" DECIMAL NOT NULL,
	"SV" DECIMAL NOT NULL,
	"IPouts" DECIMAL NOT NULL,
	"HA" DECIMAL NOT NULL,
	"HRA" DECIMAL NOT NULL,
	"BBA" DECIMAL NOT NULL,
	"SOA" DECIMAL NOT NULL,
	"E" DECIMAL NOT NULL,
	"DP" DECIMAL,
	"FP" DECIMAL NOT NULL,
	"name" VARCHAR NOT NULL,
	"park" VARCHAR,
	"attendance" DECIMAL,
	"BPF" DECIMAL NOT NULL,
	"PPF" DECIMAL NOT NULL,
	"teamIDBR" VARCHAR NOT NULL,
	"teamIDlahman45" VARCHAR NOT NULL,
	"teamIDretro" VARCHAR NOT NULL
);


CREATE TABLE "teams_franchises" (
	"franchID" VARCHAR NOT NULL,
	"franchName" VARCHAR NOT NULL,
	"active" BOOLEAN,
	"NAassoc" VARCHAR
);


CREATE TABLE "teams_half" (
	"yearID" DECIMAL NOT NULL,
	"lgID" VARCHAR NOT NULL,
	"teamID" VARCHAR NOT NULL,
	"Half" DECIMAL NOT NULL,
	"divID" VARCHAR NOT NULL,
	"DivWin" BOOLEAN NOT NULL,
	"Rank" DECIMAL NOT NULL,
	"G" DECIMAL NOT NULL,
	"W" DECIMAL NOT NULL,
	"L" DECIMAL NOT NULL
);
